on:
    push:
        branches: '**'
        tags: '' # Restrict to blank tags
    pull_request:

jobs:
 j1:
    name: Windows
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v3
    - run: cmake . && cmake --build . --config Release --target Test_devices --parallel
      shell: cmd

 j2:
    name: Windows MinGW 8.1.0 x64
    runs-on: windows-2019
    steps: 
    - uses: actions/checkout@v3
    - run: cmake -G "MSYS Makefiles" -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel
      shell: bash

 j3:
    name: Windows MinGW 8.1.0 x86
    runs-on: windows-2019
    steps: 
    - uses: actions/checkout@v3
    - run: |
        choco install -y -r --no-progress mingw --version=8.1.0 --force --x86
        choco install -y -r --no-progress make --force --x86
        echo C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin>>%GITHUB_PATH%
      shell: cmd
    - run: cmake -G "MSYS Makefiles" -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel
      shell: cmd

 j4:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v3
    - run: cmake  . && cmake --build .
#    - run: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel

 j5:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps: 
    - uses: actions/checkout@v3
    - run: cmake  . && cmake --build .

 j6:
    name: macOS Monterey
    runs-on: macos-12
    steps: 
    - uses: actions/checkout@v3
    - run: cmake  . && cmake --build .
#    - run: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel

 j7:
    name: macOS Big Sur
    runs-on: macos-11
    steps: 
    - uses: actions/checkout@v3
    - run: cmake  . && cmake --build .

 j8:
    name: Ubuntu (other tests)
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: make && make clean && cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build .

 j9:
    name: Ubuntu 20.04 Qt
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get -q update || true # Allowed to fail...
        sudo apt-get -y install qt5-default
    - run: qmake && make

 j10:
    name: Windows Qt MinGW
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v3
    - run: |
        choco install -y -r --no-progress qt5-default make
        echo C:\Qt\5.15.2\mingw81_64\bin>>%GITHUB_PATH%
      shell: cmd
    - run: qmake && make
      shell: cmd
