on:
    push:
        branches: '**'
        tags: '' # Restrict to blank tags
    pull_request:

jobs:
 j1:
    name: Windows
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v4
    - run: cmake . && cmake --build . --config Release --target Test_devices --parallel
      shell: cmd

 j2:
    name: Windows MinGW x64
    runs-on: windows-2022
    steps: 
    - uses: actions/checkout@v4
    - run: cmake -G "MSYS Makefiles" -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel
      shell: bash

 j3:
    name: Windows MinGW 13.2.0 x86
    runs-on: windows-2022
    steps: 
    - uses: actions/checkout@v4
    - run: |
        choco install -y -r --no-progress mingw --version=13.2.0 --force --x86
        choco install -y -r --no-progress make --force --x86
        echo C:\ProgramData\mingw64\mingw32\bin>>%GITHUB_PATH%
      shell: cmd
    - run: cmake -G "MSYS Makefiles" -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel
      shell: cmd

 j4:
    name: Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps: 
    - uses: actions/checkout@v4
    - run: cmake  . && cmake --build .

 j5:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps: 
    - uses: actions/checkout@v4
    - run: cmake  . && cmake --build .
#    - run: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel

 j6:
    name: macOS Sequoia
    runs-on: macos-15
    steps: 
    - uses: actions/checkout@v4
    - run: cmake  . && cmake --build .

 j7:
    name: macOS Ventura
    runs-on: macos-13
    steps: 
    - uses: actions/checkout@v4
    - run: cmake  . && cmake --build .
#    - run: cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build . --parallel

 j8:
    name: Ubuntu (other tests)
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - run: make && make clean && cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build .

 j9:
    name: Ubuntu 24.04 Qt
    runs-on: ubuntu-24.04
    steps: 
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get -q update || true # Allowed to fail...
        sudo apt-get -y install qt6-base-dev
    - run: qmake6 && make

 j10:
    name: Windows Qt MinGW
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v4
    - run: |
        choco install -y -r --no-progress qt6-base-dev make
        echo C:\Qt\6.4.2\mingw_64\bin>>%GITHUB_PATH%
      shell: cmd
    - run: qmake6 && make
      shell: cmd
